wood_wall:
    class: wall
    health: 2000

stone_wall:
    class: wall
    health: 3500

gold_wall:
    class: wall
    health: 4500

diamond_wall:
    class: wall
    health: 6000

amethyst_wall:
    class: wall
    health: 7500

wood_door:
    class: door
    health: 2000

stone_door:
    class: door
    health: 3500

gold_door:
    class: door
    health: 4500

diamond_door:
    class: door
    health: 6000

amethyst_door:
    class: door
    health: 7500

wood_spike:
    class: spike
    damage: 20
    on_hit_damage: 5

stone_spike:
    class: spike
    damage: 30
    on_hit_damage: 10

gold_spike:
    class: spike
    damage: 40
    on_hit_damage: 15

diamond_spike:
    class: spike
    damage: 50
    on_hit_damage: 20

amethyst_spike:
    class: spike
    damage: 60
    on_hit_damage: 30

workbench:
    class: building
    health: 800

anvil:
    class: building
    health: 1000

fire_small:
    class: building
    health: 500

fire_big:
    class: building
    health: 600

fire_pit:
    class: building
    health: 1000

quick_wood_wall:
    class: wall
    health: 100

quick_stone_wall:
    class: wall
    health: 300

quick_stone_spike:
    class: spike
    health: 50
    damage: 30

quick_diamond_spike:
    class: spike
    health: 100
    damage: 50
