bandage:
    type: food
    stats:
        heal_ticks: 2

meat:
    type: food
    stats:
        hunger: 10
        health: -5
    attributes:
        movement.speed:
            op: add
            value: 1

meat_cooked:
    type: food
    stats:
        hunger: 20

blue_berry:
    type: food
    stats:
        hunger: 3

red_berry:
    type: food
    stats:
        hunger: 6
        health: -2

honey:
    type: food
    stats:
        hunger: 7

mango:
    type: food
    stats:
        hunger: 10

komodo_dragon_eye:
    type: food
    stats:
        hunger: 20
        health: -35

miracle_fruit:
    type: food
    stats:
        hunger: 35
        health: -10

bottle_water:
    type: food
    water: 35
