wooden_sword:
    materials:
        wood: 20

stone_sword:
    materials:
        wooden_sword: 1
        stone: 30

    flags:
        - crafting_table

gold_sword:
    materials:
        stone_sword: 1
        gold: 40

    flags:
        - crafting_table

diamond_sword:
    materials:
        gold_sword: 1
        diamond: 50

    flags:
        - crafting_table

amethyst_sword:
    materials:
        diamond_sword: 1
        amethyst: 60
    flags:
        - crafting_table
        - fire
