wooden_sword:
    ingredients:
        wood: 20

stone_sword:
    ingredients:
        # wooden_sword: 1
        stone: 20

gold_sword:
    ingredients:
        # stone_sword: 1
        gold: 40

    # flags:
    #     - near_crafting_table

diamond_sword:
    ingredients:
        # gold_sword: 1
        diamond: 50

    # flags:
    #     - near_crafting_table

amethyst_sword:
    ingredients:
        # diamond_sword: 1
        amethyst: 60
    # flags:
    #     - near_crafting_table
    #     - near_fire
