#* SWORD
wood_sword:
    score: 75
    duration: 6000
    ingredients:
        wood: 20

stone_sword:
    score: 250
    duration: 12000
    ingredients:
        wood_sword: 1
        stone: 30
        wood: 40
    flags:
        - near_crafting_table

gold_sword:
    score: 750
    duration: 18000
    ingredients:
        stone_sword: 1
        gold: 40
        stone: 60
        wood: 80

    flags:
        - near_anvil

diamond_sword:
    score: 1250
    duration: 25000
    ingredients:
        gold_sword: 1
        diamond: 50
        gold: 70
        stone: 90

    flags:
        - near_crafting_table
        - near_anvil

amethyst_sword:
    score: 2000
    duration: 40000
    ingredients:
        diamond_sword: 1
        amethyst: 60
        diamond: 50
        gold: 40
        stone: 40
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

#* PICKAXE

wood_pickaxe:
    score: 50
    duration: 3000
    ingredients:
        wood: 10

stone_pickaxe:
    score: 150
    duration: 8000
    ingredients:
        wood_pickaxe: 1
        stone: 20
        wood: 30

    flags:
        - near_crafting_table

gold_pickaxe:
    score: 500
    duration: 12000
    ingredients:
        stone_pickaxe: 1
        gold: 20
        stone: 30
        wood: 50

    flags:
        - near_anvil

diamond_pickaxe:
    score: 1000
    duration: 18000
    ingredients:
        gold_pickaxe: 1
        diamond: 30
        gold: 40
        stone: 80

    flags:
        - near_crafting_table
        - near_anvil

amethyst_pickaxe:
    score: 1500
    duration: 25000
    ingredients:
        diamond_pickaxe: 1
        amethyst: 30
        diamond: 40
        gold: 60
        stone: 100
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

lumber_axe:
    score: 3000
    duration: 40000
    ingredients:
        diamond_pickaxe: 1
        amethyst: 40
        diamond: 40
        gold: 60
        stone: 100
        wood: 200

    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

butcher_knife:
    score: 1500
    duration: 15000
    ingredients:
        stone: 70
        wood: 100
        elephant_tusk: 2

    flags:
        - near_crafting_table
        - near_anvil

shovel:
    score: 150
    duration: 12000
    ingredients:
        stone: 70
        wood: 40

    flags:
        - near_crafting_table

# * SPEARS

stone_spear:
    score: 250
    duration: 14000
    ingredients:
        stone: 20
        wood: 80

    flags:
        - near_crafting_table

gold_spear:
    score: 750
    duration: 20000
    ingredients:
        stone_spear: 1
        gold: 30
        stone: 40
        wood: 100

    flags:
        - near_anvil

diamond_spear:
    score: 1250
    duration: 25000
    ingredients:
        gold_spear: 1
        diamond: 40
        gold: 50
        wood: 120

    flags:
        - near_crafting_table
        - near_anvil

amethyst_spear:
    score: 2000
    duration: 40000
    ingredients:
        diamond_spear: 1
        amethyst: 40
        diamond: 50
        gold: 60
        stone: 140
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

tusk_spear:
    score: 4000
    duration: 60000
    ingredients:
        diamond_spear: 1
        elephant_tusk: 4
        amethyst: 20
        gold: 60
        wood: 140
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

# * Hammers

stone_hammer:
    score: 500
    duration: 10000
    ingredients:
        stone: 100
        wood: 60

    flags:
        - near_crafting_table

gold_hammer:
    score: 1000
    duration: 18000
    ingredients:
        stone_hammer: 1
        gold: 100
        stone: 80
        wood: 60

    flags:
        - near_anvil
        - near_crafting_table

diamond_hammer:
    score: 1500
    duration: 30000
    ingredients:
        gold_hammer: 1
        diamond: 120
        gold: 100
        stone: 80

    flags:
        - near_crafting_table
        - near_anvil

amethyst_hammer:
    score: 2500
    duration: 50000
    ingredients:
        diamond_hammer: 1
        amethyst: 120
        diamond: 100
        gold: 100
        stone: 80
        wood: 80
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

#* Helmets

wood_helmet:
    score: 75
    duration: 10000
    ingredients:
        wood: 50

stone_helmet:
    score: 200
    duration: 20000
    ingredients:
        wood_helmet: 1
        stone: 80
        wood: 60

    flags:
        - near_crafting_table

gold_helmet:
    score: 500
    duration: 30000
    ingredients:
        stone_helmet: 1
        gold: 80
        stone: 60
        wood: 40

    flags:
        - near_anvil

diamond_helmet:
    score: 1250
    duration: 40000
    ingredients:
        gold_helmet: 1
        diamond: 80
        gold: 60
        stone: 40

    flags:
        - near_crafting_table
        - near_anvil

amethyst_helmet:
    score: 2500
    duration: 50000
    ingredients:
        diamond_helmet: 1
        amethyst: 80
        diamond: 60
        gold: 40
        stone: 80
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

# * Fur Crafts

pitch:
    score: 50
    duration: 1000
    ingredients:
        pinecone: 1
        honey: 1

    flags:
        - near_fire

cloth:
    score: 75
    duration: 2000
    ingredients:
        pitch: 1
        deer_hide: 1
        wood: 10

    flags:
        - near_fire
        - near_crafting_table

backpack:
    score: 600
    duration: 14000
    ingredients:
        deer_hide: 2
        cloth: 2
        bear_fur: 8

    flags:
        - near_crafting_table

bandage:
    score: 75
    duration: 2000
    ingredients:
        cloth: 1
        honey: 1
    flags:
        - near_crafting_table

book:
    score: 500
    duration: 7000
    ingredients:
        deer_hide: 2
        pitch: 2
        bear_fur: 4
    flags:
        - near_crafting_table

resource_book:
    score: 4000
    duration: 40000
    ingredients:
        book: 1
        amethyst: 80
        diamond: 100
        gold: 120
        stone: 140
        wood: 200
    flags:
        - near_crafting_table
        - near_anvil
        - near_fire

time_book:
    score: 4000
    duration: 40000
    ingredients:
        book: 1
        cloth: 8
        ram_wool: 12
        bear_fur: 12
        komodo_dragon_eye: 4
        elephant_tusk: 2
        wood: 200
    flags:
        - near_crafting_table
        - near_fire

earmuffs:
    score: 250
    duration: 6000
    ingredients:
        bear_fur: 2
        deer_hide: 3
    flags:
        - near_crafting_table

beanie:
    score: 300
    duration: 12000
    ingredients:
        bear_fur: 6
        deer_hide: 2
        cloth: 2

    flags:
        - near_crafting_table

coat:
    score: 1200
    duration: 18000
    ingredients:
        ram_wool: 8
        bear_fur: 6
        pitch: 2

    flags:
        - near_crafting_table

# * BUILDINGS

#Walls

wood_wall:
    score: 15
    duration: 2000
    ingredients:
        wood: 25

stone_wall:
    score: 50
    duration: 2500
    ingredients:
        wood_wall: 1
        stone: 23
        wood: 13
    flags:
        - near_crafting_table

gold_wall:
    score: 65
    duration: 3000
    ingredients:
        stone_wall: 1
        gold: 21
        stone: 11

    flags:
        - near_anvil

diamond_wall:
    score: 85
    duration: 5000
    ingredients:
        gold_wall: 1
        diamond: 19
        gold: 9

    flags:
        - near_crafting_table
        - near_anvil

amethyst_wall:
    score: 100
    duration: 6000
    ingredients:
        diamond_wall: 1
        amethyst: 17
        diamond: 7
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

#Doors

wood_door:
    score: 25
    duration: 3000
    ingredients:
        wood: 30

stone_door:
    score: 50
    duration: 3500
    ingredients:
        wood_door: 1
        stone: 28
        wood: 18
    flags:
        - near_crafting_table

gold_door:
    score: 75
    duration: 4500
    ingredients:
        stone_door: 1
        gold: 26
        stone: 16

    flags:
        - near_anvil

diamond_door:
    score: 100
    duration: 6000
    ingredients:
        gold_door: 1
        diamond: 24
        gold: 14

    flags:
        - near_crafting_table
        - near_anvil

amethyst_door:
    score: 125
    duration: 7000
    ingredients:
        diamond_door: 1
        amethyst: 22
        diamond: 12
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

#spike

wood_spike:
    score: 100
    duration: 6000
    ingredients:
        wood: 70

stone_spike:
    score: 125
    duration: 7000
    ingredients:
        wood_spike: 1
        stone: 60
        wood: 40
    flags:
        - near_crafting_table

gold_spike:
    score: 150
    duration: 8000
    ingredients:
        stone_spike: 1
        gold: 50
        stone: 45

    flags:
        - near_anvil

diamond_spike:
    score: 300
    duration: 9000
    ingredients:
        gold_spike: 1
        diamond: 40
        gold: 50

    flags:
        - near_crafting_table
        - near_anvil

amethyst_spike:
    score: 450
    duration: 10000
    ingredients:
        diamond_spike: 1
        amethyst: 30
        diamond: 55
    flags:
        - near_crafting_table
        - near_fire
        - near_anvil

#other buildings

workbench:
    score: 75
    duration: 3000
    ingredients:
        wood: 20
        stone: 10

anvil:
    score: 200
    duration: 5000
    ingredients:
        wood: 20
        stone: 50

    flags:
        - near_crafting_table

fire_small:
    score: 50
    duration: 3000
    ingredients:
        wood: 15
        stone: 5

fire_big:
    score: 150
    duration: 6000
    ingredients:
        wood: 35
        stone: 15

fire_pit:
    score: 200
    duration: 8000
    ingredients:
        wood: 50
        stone: 50

    flags:
        - near_crafting_table

quick_wood_wall:
    score: 25
    duration: 1000
    ingredients:
        wood: 20

quick_stone_wall:
    score: 50
    duration: 2000
    ingredients:
        quick_wood_wall: 1
        stone: 20

    flags:
        - near_crafting_table

quick_stone_spike:
    score: 100
    duration: 5000
    ingredients:
        stone: 30
        tooth: 2

    flags:
        - near_crafting_table

quick_diamond_spike:
    score: 250
    duration: 7000
    ingredients:
        diamond: 30
        tooth: 4

    flags:
        - near_crafting_table
        - near_anvil

meat_cooked:
    score: 35
    duration: 2000
    ingredients:
        meat: 1

    flags:
        - near_fire

miracle_fruit:
    score: 200
    duration: 7000
    ingredients:
        blue_berry: 5
        honey: 2
        amethyst: 10
        diamond: 15

tooth:
    score: 20
    amount: 4
    duration: 6000
    ingredients:
        elephant_tusk: 1

    flags:
        - near_crafting_table

bird_skull:
    score: 2000
    duration: 15000
    ingredients:
        tooth: 1
        cloth: 5
        pitch: 8
        deer_hide: 6
        meat: 25

    flags:
        - near_crafting_table
        - near_fire

repair_hammer:
    score: 500
    duration: 6000
    ingredients:
        stone: 50
        wood: 75

    flags:
        - near_crafting_table
        - near_anvil

diamond_repair_hammer:
    score: 1000
    duration: 15000
    ingredients:
        repair_hammer: 1
        stone: 100
        diamond: 40


    flags:
        - near_crafting_table
        - near_anvil
        - near_fire


bottle_empty:
    score: 150
    duration: 5000
    ingredients:
        sand: 40

    flags:
        - near_crafting_table
        - near_fire

bottle_water:
    score: 0
    duration: 2500

    flags:
        - in_water

bottle_water:
    score: 50
    duration: 3000
    ingredients:
        ice: 15

    flags:
        - near_fire

tent:
    score: 500
    duration: 12000
    ingredients:
        wood: 300
        cloth: 10

    flags:
        - near_crafting_table

scuba:
    score: 2500
    duration: 20000
    ingredients:
        fish_scale: 15
        diamond: 50
        stone: 75
        

    flags:
        - near_crafting_table
        - near_anvil

alligator_helmet:
    score: 5000
    duration: 35000
    ingredients:
        alligator_skin: 6
        fish_scale: 6
        komodo_dragon_eye: 2
        gold_helmet: 1
        
    flags:
        - near_crafting_table
        - in_water
        - near_anvil
