# anger = 0: scared, 1: no reaction, 2: agressive

elephant:
    anger: 2
    speed: 0.5
    attack_damage: 5
    size: 6
    wander_range: 5000
    rest_time: 100

bear:
    size: 4
    speed: 7
    wander_range: 5000
    rest_time: 1

ram:
    speed: 10
    size: 3
    wander_range: 3000
    rest_time: 1
