# anger = 0: scared, 1: no reaction, 2: agressive

elephant:
    anger: 2
    speed: 2
    attack_damage: 50
    size: 6
    wander_range: 75
    rest_time: 1
    spawns: elephant_dead




bear:
    size: 4
    speed: 1
    wander_range: 105
    rest_time: 0.3

ram:
    speed: 2
    size: 3
    wander_range: 110
    rest_time: 0.25
