helmet:
    function: wear

hat:
    function: wear

pickaxe:
    function: main_hand
    attack_reach: 10
    attack_sweep: 30
    attack_origin: 15

knife:
    speed_multiplier: 0.8
    function: main_hand

sword:
    speed_multiplier: 0.8
    function: main_hand
    attack_origin: 15
    attack_reach: 15
    attack_sweep: 30

book:
    function: off_hand

building:
    function: building

food:
    function: consume

spear:
    speed_multiplier: 0.8
    function: main_hand
    attack_reach: 15
    attack_sweep: 30
    attack_origin: 45

hammer:
    function: main_hand
