book:
    type: book

resource_book:
    type: book

time_book:
    type: book

bird_skull:
    type: book
    function: off_hand
    atributes:
        attack.damage.animal:
            op: add
            value: 15
