wood:
    score: 1
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 0
    regen_speed: 10
    items:
        wood: 10
        stone: 10
        gold: 10
        diamond: 10
        amethyst: 10
