forest_tree:
    tool: pickaxe
    level: 0
    regen_speed: 10
    amount: 50
    item: wood

pine_tree:
    tool: pickaxe
    level: 0
    regen_speed: 10
    amount: 50
    item: wood

savanah_tree:
    tool: pickaxe
    level: 0
    regen_speed: 10
    amount: 50
    item: wood

bush:
    tool: pickaxe
    level: 0
    regen_speed: 10
    amount: 50
    item: wood



stone:
    tool: pickaxe
    level: 1
    regen_speed: 20
    amount: 40
    item: stone

gold:
    tool: pickaxe
    level: 2
    regen_speed: 30
    amount: 30
    item: gold

diamond:
    tool: pickaxe
    level: 3
    regen_speed: 40
    amount: 20
    item: diamond

amethyst:
    tool: pickaxe
    level: 4
    regen_speed: 50
    amount: 10
    item: amethyst
