pine_tree:
    score: 5
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 0
    regen_speed: 5
    items:
        wood: 30

pine_tree_snow:
    score: 5
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 0
    regen_speed: 5
    items:
        wood: 30

forest_tree:
    score: 5
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 0
    regen_speed: 5
    items:
        wood: 40

savanah_tree:
    score: 5
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 0
    regen_speed: 7
    items:
        wood: 80

stone:
    score: 8
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 1
    regen_speed: 8
    items:
        stone: 30

gold:
    score: 10
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 2
    regen_speed: 10
    items:
        gold: 20

diamond:
    score: 20
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 3
    regen_speed: 14
    items:
        diamond: 20

amethyst:
    score: 30
    exclusive: true
    multipliers:
        pickaxe: 1
    level: 4
    regen_speed: 17
    items:
        amethyst: 20

bear_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 3
        bear_fur: 1

deer_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 2
        deer_hide: 1

raindeer_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 4
        deer_hide: 2

ram_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 3
        ram_wool: 1

elephant_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 8
        elephant_tusk: 1

alligator_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 4
        alligator_skin: 1
        tooth: 2

komodo_dragon_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 6
        komodo_dragon_eye: 1
        tooth: 4

bee_dead:
    duration: 30

queen_bee_dead:
    duration: 30
    multipliers:
        knife: 2
    items:
        meat: 2

hive_small:
    destroy_on_empty: true
    score: 20
    items:
        honey: 4

hive_medium:
    destroy_on_empty: true
    score: 20
    items:
        honey: 7

hive_large:
    destroy_on_empty: true
    score: 20
    items:
        honey: 10

player_dead:
    destroy_on_empty: true
    items:
        #player inventoy
