wood:
    level: 0
    regen_speed: 10
    amount: 50
    item: wood

stone:
    level: 1
    regen_speed: 20
    amount: 40
    item: stone

gold:
    level: 2
    regen_speed: 30
    amount: 30
    item: gold

diamond:
    level: 3
    regen_speed: 40
    amount: 20
    item: diamond

amethyst:
    level: 4
    regen_speed: 50
    amount: 10
    item: amethyst
