helmet:
    function: wear

hat:
    function: wear

pickaxe:
    function: main_hand

knife:
    function: main_hand

sword:
    speed_multiplier: 0.9
    function: main_hand

book:
    function: off_hand

wall:
    function: building

food:
    function: consume

spear:
    function: main_hand

hammer:
    function: main_hand
