wood_helmet:
    type: helmet
    defense: 2
    level: 1

stone_helmet:
    type: helmet
    defense: 3
    level: 2

gold_helmet:
    type: helmet
    defense: 5
    level: 3

diamond_helmet:
    type: helmet
    defense: 6
    level: 4

amethyst_helmet:
    type: helmet
    level: 5

    defense: 7

earmuffs:
    type: hat
    attributes:
        temperature.warmth:
            op: add
            value: 7

beanie:
    type: hat
    attributes:
        temperature.warmth:
            op: add
            value: 12

coat:
    type: hat
    attributes:
        temperature.warmth:
            op: add
            value: 24
