wood_helmet:
    type: helmet
    defense: 2
    level: 1

stone_helmet:
    type: helmet
    defense: 3
    level: 2

gold_helmet:
    type: helmet
    defense: 5
    level: 3

diamond_helmet:
    type: helmet
    defense: 6
    level: 4

amethyst_helmet:
    type: helmet
    defense: 7
    level: 5

earmuffs:
    type: hat
    warmth: 7
    speed_multiplier: 2

beanie:
    type: hat
    warmth: 15

coat:
    type: hat
    warmth: 24
