wood_helmet:
    type: helmet
    level: 1
    attributes:
        health.defense:
            op: add
            value: 2
    stats:
        health: -10

stone_helmet:
    type: helmet
    level: 2
    attributes:
        health.defense:
            op: add
            value: 3

gold_helmet:
    type: helmet
    level: 3
    attributes:
        health.defense:
            op: add
            value: 5

diamond_helmet:
    type: helmet
    level: 4
    attributes:
        health.defense:
            op: add
            value: 6

amethyst_helmet:
    type: helmet
    level: 5

    attributes:
        health.defense:
            op: add
            value: 7

earmuffs:
    type: hat
    attributes:
        temperature.warmth:
            op: add
            value: 7

beanie:
    type: hat
    attributes:
        temperature.warmth:
            op: add
            value: 12

coat:
    type: hat
    attributes:
        temperature.warmth:
            op: add
            value: 24
