import visualDef0 from "./defs/actors/alligator.yml";
import visualDef1 from "./defs/actors/animal.yml";
import visualDef2 from "./defs/actors/bear.yml";
import visualDef3 from "./defs/actors/bee.yml";
import visualDef4 from "./defs/actors/deer.yml";
import visualDef5 from "./defs/actors/elephant.yml";
import visualDef6 from "./defs/actors/komodo_dragon.yml";
import visualDef7 from "./defs/actors/player.yml";
import visualDef8 from "./defs/actors/queen_bee.yml";
import visualDef9 from "./defs/actors/raindeer.yml";
import visualDef10 from "./defs/actors/ram.yml";
import visualDef11 from "./defs/base/rottable.yml";
import visualDef12 from "./defs/base/single_tile_node.yml";
import visualDef13 from "./defs/corpses/alligator_dead.yml";
import visualDef14 from "./defs/corpses/bear_dead.yml";
import visualDef15 from "./defs/corpses/bee_dead.yml";
import visualDef16 from "./defs/corpses/corpse.yml";
import visualDef17 from "./defs/corpses/deer_dead.yml";
import visualDef18 from "./defs/corpses/elephant_dead.yml";
import visualDef19 from "./defs/corpses/komodo_dragon_dead.yml";
import visualDef20 from "./defs/corpses/queen_bee_dead.yml";
import visualDef21 from "./defs/corpses/raindeer_dead.yml";
import visualDef22 from "./defs/corpses/ram_dead.yml";
import visualDef23 from "./defs/doors/amethyst_door.yml";
import visualDef24 from "./defs/doors/diamond_door.yml";
import visualDef25 from "./defs/doors/door.yml";
import visualDef26 from "./defs/doors/gold_door.yml";
import visualDef27 from "./defs/doors/stone_door.yml";
import visualDef28 from "./defs/doors/wood_door.yml";
import visualDef29 from "./defs/nature/tree.yml";
import visualDef30 from "./defs/structures/point_generator.yml";
import visualDef31 from "./defs/structures/structure.yml";

// Generated by scripts/generate-visual-defs.ts. Do not edit by hand.
export const bundledVisualDefs: Record<string, unknown> = {
    "actors/alligator.yml": visualDef0,
    "actors/animal.yml": visualDef1,
    "actors/bear.yml": visualDef2,
    "actors/bee.yml": visualDef3,
    "actors/deer.yml": visualDef4,
    "actors/elephant.yml": visualDef5,
    "actors/komodo_dragon.yml": visualDef6,
    "actors/player.yml": visualDef7,
    "actors/queen_bee.yml": visualDef8,
    "actors/raindeer.yml": visualDef9,
    "actors/ram.yml": visualDef10,
    "base/rottable.yml": visualDef11,
    "base/single_tile_node.yml": visualDef12,
    "corpses/alligator_dead.yml": visualDef13,
    "corpses/bear_dead.yml": visualDef14,
    "corpses/bee_dead.yml": visualDef15,
    "corpses/corpse.yml": visualDef16,
    "corpses/deer_dead.yml": visualDef17,
    "corpses/elephant_dead.yml": visualDef18,
    "corpses/komodo_dragon_dead.yml": visualDef19,
    "corpses/queen_bee_dead.yml": visualDef20,
    "corpses/raindeer_dead.yml": visualDef21,
    "corpses/ram_dead.yml": visualDef22,
    "doors/amethyst_door.yml": visualDef23,
    "doors/diamond_door.yml": visualDef24,
    "doors/door.yml": visualDef25,
    "doors/gold_door.yml": visualDef26,
    "doors/stone_door.yml": visualDef27,
    "doors/wood_door.yml": visualDef28,
    "nature/tree.yml": visualDef29,
    "structures/point_generator.yml": visualDef30,
    "structures/structure.yml": visualDef31,
};
