const visualDir = `${import.meta.dir}/../packages/client/src/visual`;
const defsDir = `${visualDir}/defs`;
const output = `${visualDir}/generated_defs.ts`;

export async function generateVisualDefs(): Promise<void> {
    const files = [...new Bun.Glob("**/*.yml").scanSync({ cwd: defsDir })].sort();
    const imports = files.map(
        (file, index) => `import visualDef${index} from "./defs/${file}";`
    );
    const entries = files.map(
        (file, index) => `    ${JSON.stringify(file)}: visualDef${index},`
    );
    const source = `${imports.join("\n")}

// Generated by scripts/generate-visual-defs.ts. Do not edit by hand.
export const bundledVisualDefs: Record<string, unknown> = {
${entries.join("\n")}
};
`;
    const current = await Bun.file(output).text().catch(() => "");
    if (current !== source) await Bun.write(output, source);
}

if (import.meta.main) await generateVisualDefs();
