tools:
    types:
        - pickaxe
        - sword
        - helmet
        - spear
        - hammer
        - hat
        - book
    items:
        - spyglass

buildings:
    types:
        - wall
        - door
        - building
        - spike
