unknown_asset:
    type: none
    sprite: unknown_asset

# Pickaxe
wood_pickaxe:
    type: pickaxe
    sprite: wood_pickaxe

stone_pickaxe:
    type: pickaxe
    sprite: stone_pickaxe

gold_pickaxe:
    type: pickaxe
    sprite: gold_pickaxe

diamond_pickaxe:
    type: pickaxe
    sprite: diamond_pickaxe

amethyst_pickaxe:
    type: pickaxe
    sprite: amethyst_pickaxe

butcher_knife:
    type: pickaxe
    sprite: butcher_knife

lumber_axe:
    type: pickaxe
    sprite: lumber_axe

shovel:
    type: pickaxe
    sprite: shovel

# Sword
wood_sword:
    type: sword
    sprite: wood_sword

stone_sword:
    type: sword
    sprite: stone_sword

gold_sword:
    type: sword
    sprite: gold_sword

diamond_sword:
    type: sword
    sprite: diamond_sword

amethyst_sword:
    type: sword
    sprite: amethyst_sword

# spears

stone_spear:
    type: spear
    sprite: stone_spear

gold_spear:
    type: spear
    sprite: gold_spear

diamond_spear:
    type: spear
    sprite: diamond_spear

amethyst_spear:
    type: spear
    sprite: amethyst_spear

tusk_spear:
    type: spear
    sprite: tusk_spear

# Helmet
wood_helmet:
    type: helmet
    sprite: wood_helmet

stone_helmet:
    type: helmet
    sprite: stone_helmet

gold_helmet:
    type: helmet
    sprite: gold_helmet
    body_display:
        y: 10

diamond_helmet:
    type: helmet
    sprite: diamond_helmet

amethyst_helmet:
    type: helmet
    sprite: amethyst_helmet

# Hammer
wood_hammer:
    type: hammer
    sprite: wooden_hammer

stone_hammer:
    type: hammer
    sprite: stone_hammer

gold_hammer:
    type: hammer
    sprite: gold_hammer

diamond_hammer:
    type: hammer
    sprite: diamond_hammer

amethyst_hammer:
    type: hammer
    sprite: amethyst_hammer

# * BUILDINGs

# Walls

wood_wall:
    type: wall
    sprite: wooden_wall

stone_wall:
    type: wall
    sprite: stone_wall

gold_wall:
    type: wall
    sprite: gold_wall

diamond_wall:
    type: wall
    sprite: diamond_wall

amethyst_wall:
    type: wall
    sprite: amethyst_wall

# Door

wood_door:
    type: door
    sprite: wooden_door

stone_door:
    type: door
    sprite: stone_door

gold_door:
    type: door
    sprite: gold_door

diamond_door:
    type: door
    sprite: diamond_door

amethyst_door:
    type: door
    sprite: amethyst_door

# spike

wood_spike:
    type: spike
    sprite: wooden_spike

stone_spike:
    type: spike
    sprite: stone_spike

gold_spike:
    type: spike
    sprite: gold_spike

diamond_spike:
    type: spike
    sprite: diamond_spike

amethyst_spike:
    type: spike
    sprite: amethyst_spike

# buildings

workbench:
    type: building
    sprite: workbench

anvil:
    type: building
    sprite: anvil

fire_pit:
    type: building
    sprite: fire_pit

fire_big:
    type: building
    sprite: fire_big

fire_small:
    type: building
    sprite: fire_small

earmuffs:
    type: hat
    sprite: earmuffs

beanie:
    type: hat
    sprite: beanie

coat:
    type: hat
    sprite: coat

book:
    type: book
    sprite: book

resource_book:
    type: book
    sprite: resource_book

time_book:
    type: book
    sprite: time_book

