unknown_asset: unknown_asset.svg

player: player.svg
hand: hand.svg

wooden_pickaxe: wooden_pickaxe.svg
stone_pickaxe: stone_pickaxe.svg
gold_pickaxe: gold_pickaxe.svg
diamond_pickaxe: diamond_pickaxe.svg
amethyst_pickaxe: amethyst_pickaxe.svg

wooden_sword: wooden_sword.svg
stone_sword: stone_sword.svg
gold_sword: gold_sword.svg
diamond_sword: diamond_sword.svg
amethyst_sword: amethyst_sword.svg

amethyst_spear: amethyst_spear.svg

wooden_helmet: wooden_helmet.svg
stone_helmet: stone_helmet.svg
gold_helmet: gold_helmet.svg
diamond_helmet: diamond_helmet.svg
amethyst_helmet: amethyst_helmet.svg

wood: flame2.png
stone: stone.svg
gold: gold.svg
diamond: diamond.svg
amethyst: amethyst.svg

weapon_toggle: weapon_toggle.svg
build_toggle: build_toggle.svg
misc_toggle: misc_toggle.svg

elephant: elephant.svg
bear: bear.svg
ram: ram.svg
