unknown_asset: unknown_asset

wooden_pickaxe: wooden_pickaxe
stone_pickaxe: stone_pickaxe
gold_pickaxe: gold_pickaxe
diamond_pickaxe: diamond_pickaxe
amethyst_pickaxe: amethyst_pickaxe

wooden_sword: wooden_sword
stone_sword: stone_sword
gold_sword: gold_sword
diamond_sword: diamond_sword
amethyst_sword: amethyst_sword

amethyst_spear: amethyst_spear

wooden_helmet: wooden_helmet
stone_helmet: stone_helmet
gold_helmet: gold_helmet
diamond_helmet: diamond_helmet
amethyst_helmet: amethyst_helmet

wood: acacia3
stone: stone
gold: gold
diamond: diamond
amethyst: amethyst

weapon_toggle: weapon_toggle
build_toggle: build_toggle
misc_toggle: misc_toggle

elephant: elephant
bear: bear
ram: ram
